/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://4ra3hr2b2vfkfdpmgnvzzmk5oa.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nee2phra4zdedigca7wq7nqeb4",
    "aws_cognito_identity_pool_id": "eu-north-1:301fa828-b854-4c8b-94c9-e764f5235614",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_UB3mzFKYU",
    "aws_user_pools_web_client_id": "6h4fa22rr1cb64tjlm8m3mfngp",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
